services:
  - docker

stages:
  - name: build_arm64
    if: type != pull_request AND tag IS present
  - name: build_amd64
    if: type != pull_request AND tag IS present
  - name: build_ppc64le
    if: type != pull_request AND tag IS present

matrix:
  include:
    - stage: build_arm64
      services:
        - docker
      os: linux
      arch: arm64
      env: 
        - COMMON_IMAGE_TAG=${TRAVIS_TAG}
        - DOCKER_REGISTRY=quay.io/datashim
      # trigger build foo
      install: echo "no install"
      script: cd build-tools && ./build_components.sh && ./build_csi_plugins.sh && ./build_sidecars.sh
    - stage: build_amd64
      services:
        - docker
      os: linux
      arch: amd64
      dist: bionic
      env: 
        - COMMON_IMAGE_TAG=${TRAVIS_TAG}
        - DOCKER_REGISTRY=quay.io/datashim
      # trigger build foo
      install: echo "no install"
      script: cd build-tools && ./build_components.sh && ./build_csi_plugins.sh && ./build_sidecars.sh
    - stage: build_ppc64le
      services:
        - docker
      os: linux
      arch: ppc64le
      env: 
        - COMMON_IMAGE_TAG=${TRAVIS_TAG}
        - DOCKER_REGISTRY=quay.io/datashim
      # trigger build foo
      install: echo "no install"
      script: cd build-tools && ./build_components.sh && ./build_csi_plugins.sh && ./build_sidecars.sh