---
apiVersion: v1
kind: Pod
metadata:
  name: dlf-spark
spec:
  template:
    metadata:
      labels:
        dataset.0.id: "bookds"
        dataset.0.useas: "mount"
    spec:
      containers:
      - name: dlf-spark        
