---
apiVersion: v1
kind: Service
metadata:
  name: spark-dlf-svc
spec:
  type: "ClusterIP"
  clusterIP: "None"
  selector:
    app: spark-dlf-driver
  ports:
    - port: 20020
      targetPort: 20020
      name: spark-driver
---
apiVersion: v1
kind: Service
metadata:
  name: spark-driver-ui
spec:
  type: "NodePort"
  selector:
    app: spark-dlf-driver
  ports:
    - port: 8966
      targetPort: 4040
      name: spark-ui
---
apiVersion: v1
kind: Pod
metadata:
  name: spark-dlf-driver
  labels:
    app: spark-dlf-driver
    dataset.0.id: "bookds"
    dataset.0.useas: "configmap"
spec:
  serviceAccountName: spark-dlf
  containers:
    - name: pyspark
      image: ${DOCKER_REGISTRY_COMPONENTS}/spark-py:v${spark_version}
      imagePullPolicy: IfNotPresent
      args:
        - /opt/spark/bin/spark-submit
        - --master
        - k8s://https://$(KUBERNETES_PORT_443_TCP_ADDR):$(KUBERNETES_PORT_443_TCP_PORT)
        - --deploy-mode
        - client
        - --conf
        - spark.executor.instances=1
        - --conf
        - spark.kubernetes.container.image=${DOCKER_REGISTRY_COMPONENTS}/spark-py:v${spark_version}
        - --conf
        - spark.kubernetes.namespace=${DATASET_OPERATOR_NAMESPACE}
        - --conf
        - spark.kubernetes.authenticate.driver.serviceAccountName=spark-dlf
        - --conf
        - spark.kubernetes.driver.pod.name=spark-dlf-driver
        - --conf
        - spark.driver.host=spark-dlf-svc.${DATASET_OPERATOR_NAMESPACE}.svc.cluster.local
        - --conf
        - spark.driver.port=20020
        - --conf
        - spark.kubernetes.container.image.pullSecrets=${DOCKER_REGISTRY_SECRET}
        - --conf
        - spark.jars.ivy=/tmp/.ivy
        - local:///opt/spark/examples/example_dlf.py
  imagePullSecrets:
    - name: ${DOCKER_REGISTRY_SECRET}
